import React, { useState } from "react";
import styles from "./Landing.module.scss";
import Head from "next/head";
const Landing: React.FC = (): JSX.Element => {
	return (
		<div className={styles.landing_container}>
			{" "}
			<Head>
				<title>Eventier landing</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/logo.png" />
			</Head>
			<header className={styles.header_landing}>
				<h2>Plan the schedule with your team using Eventier!</h2>
				<p>Simply drag and drop your tasks, try yourself!</p>
			</header>
			<main className={styles.main_landing}>
				<div className={styles.left_landing}>
					<p className={styles.p_landing} style={{ color: "#DD485D" }}>
						To do
					</p>
				</div>
				<div className={styles.center_landing}>
					<p className={styles.p_landing} style={{ color: "#D3E039" }}>
						In process
					</p>
				</div>
				<div className={styles.right_landing}>
					<p className={styles.p_landing} style={{ color: "#3DCF29" }}>
						Done
					</p>
				</div>
			</main>
		</div>
	);
};

export default Landing;
